### ISSUE TITLE
code issues

### ISSUE THREAD

**Issue by GJ-JL** [846468230/SEBot#1]
Dear Author,

I hope this message finds you well. During the initial run of the code with the two dataset documents, I encountered some issues, mainly the absence of an environment configuration file as well as the data files twibot-20_4.pickle and MGTAB_4.pickle. If it is convenient for you, could you please provide these files or guide me on how to obtain them? Additionally, if there are any other related setup instructions, I would greatly appreciate your guidance.

**Comment by 846468230** [comment]
Please refer to the newly provided link in the readme
